layout_spectrum: 0.3193663839720153
typography_spectrum: 0.2884956971822436
color:
  lightness: 0.6255506092791289
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  saturation: 0.8447071150799125
  brandStrength: 0.8747085847069352
  rhythmicContrast: 0.0185957563818792
name: Kirchentag 2017
analytics:
  twitter: delgiftweets
purpose:
  - type: contact
    url: 'mailto:michael@deutschegemeinde.fi'
    label: E–Mail–Nachricht
github: true
description: >-
  36. Deutscher Evangelischer Kirchentag in Berlin – Wittenberg, vom 24.–28. Mai
  2017 — und die Deutsche Gemeinde in Finnland ist vor Ort …   'Du siehst mich'
  (1. Mose 16,13)
author: {}
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
navigation:
  - name: Zum Internetfenster der Gemeinde
    url: 'https://goo.gl/c7sXGH'
    type: external
content_rating:
  adult: false
opengraph: {}
title: Mal den Kirchentag gemeinsam erleben…
